name: Enqueue RQ test job

on:
  workflow_dispatch:

jobs:
  enqueue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install small deps
        run: |
          python -m pip install --upgrade pip
          pip install redis rq

      - name: Run enqueue script
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          python - <<'PY'
import os
from redis import Redis
from rq import Queue
url = os.environ.get("REDIS_URL")
if not url:
    raise SystemExit("No REDIS_URL provided")
conn = Redis.from_url(url)
q = Queue('default', connection=conn)
job = q.enqueue('builtins.print', 'hello from enqueue-test-job workflow')
print("Enqueued job id:", job.id)
PY
