name: Run RQ worker on-demand

on:
  workflow_dispatch:

jobs:
  run-worker:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # install project deps if you have a requirements file, otherwise install minimal deps
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install redis rq
          fi

      - name: Run rq worker in burst (process queued jobs then exit)
        shell: bash
        env:
          REDIS_URL: ${{ secrets.REDIS_URL }}
        run: |
          echo "Starting rq worker in --burst mode (verbose) for 10 minutes"
          # Use python -m rq.worker (correct) so module runs properly
          python -m rq.worker default -u "$REDIS_URL" --burst -v &
          WORKER_PID=$!
          echo "Worker started with PID $WORKER_PID"
          # let the worker run long enough to pick jobs (adjust as needed)
          sleep 600
          echo "Stopping worker (PID $WORKER_PID)"
          kill -SIGTERM $WORKER_PID || true
          wait $WORKER_PID || true
          echo "rq worker finished"
